language: 
  - node_js
node_js:
  # - "0.11"
  - "0.10"
  # - "0.8"
before_install:
  - sudo apt-get update 
  - gem update --system
  - gem install sass --version "=3.2.12"
  - gem install compass --version "=0.12.2"
  - npm install -g grunt-cli bower istanbul
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cd www
  - bower install
  - npm install
script:
  - grunt test
notifications:
  email: false
after_success:
  - cat ./coverage/PhantomJS\ 1.9.7\ \(Linux\)/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage