language: node_js
node_js:
  # - "0.11"
  - "0.10"
  # - "0.8"
before_script:
  - echo 'before_script'
  - cd www
  - npm install -g bower grunt-cli
  - bower install
after_script:
  - echo 'after_script'
  - cd ../