language: node_js
node_js:
  # - "0.11"
  - "0.10"
  # - "0.8"
before_script:
  - echo 'before_script'
  - cd www
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - echo 'after_script'
  - cd ../