language: 
  - node_js
node_js:
  # - "0.11"
  - "0.10"
  # - "0.8"
before_script:
  - sudo apt-get update
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - gem update --system
  - gem install sass --version "=3.2.12"
  - gem install compass --version "=0.12.2"
  - npm install -g grunt-cli bower
install:
  - cd www
  - bower install
  - npm install